/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GButton: typeof import('./components/shared/buttons/GButton.vue')['default']
    GButtonAdv: typeof import('./components/shared/buttons/GButtonAdv.vue')['default']
    GButtonCommon: typeof import('./components/shared/buttons/GButtonCommon.vue')['default']
    GCard: typeof import('./components/shared/g-card/GCard.vue')['default']
    GCheckbox: typeof import('./components/shared/g-checkbox/GCheckbox.vue')['default']
    GCombobox: typeof import('./components/shared/g-combobox/GCombobox.vue')['default']
    GDivider: typeof import('./components/shared/g-divider/GDivider.vue')['default']
    GHeading: typeof import('./components/shared/text/g-heading/GHeading.vue')['default']
    GInput: typeof import('./components/shared/g-input/GInput.vue')['default']
    GInputNumber: typeof import('./components/shared/g-input-number/GInputNumber.vue')['default']
    GLabel: typeof import('./components/shared/text/g-label/GLabel.vue')['default']
    GLink: typeof import('./components/shared/text/g-link/GLink.vue')['default']
    GModal: typeof import('./components/shared/g-modal/GModal.vue')['default']
    GProgress: typeof import('./components/shared/g-progress/GProgress.vue')['default']
    GRadio: typeof import('./components/shared/g-radio/GRadio.vue')['default']
    GSlider: typeof import('./components/shared/g-slider/GSlider.vue')['default']
    GText: typeof import('./components/shared/text/g-text/GText.vue')['default']
    GTextarea: typeof import('./components/shared/g-textarea/GTextarea.vue')['default']
    GToast: typeof import('./components/shared/g-toast/GToast.vue')['default']
    GToastContainer: typeof import('./components/shared/g-toast/GToastContainer.vue')['default']
    GToggle: typeof import('./components/shared/g-toggle/GToggle.vue')['default']
    GTooltip: typeof import('./components/shared/g-tooltip/GTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
